/**
 * IVA Security Validator
 * Validates and sanitizes IVA context and preferences to prevent injection attacks
 */

const CONTEXT_VERSION = '1.0';

// Whitelist of allowed values
const ALLOWED_VALUES = {
    business_type: ['services', 'retail', 'manufacturing', 'personal', 'consultoria', 'general'],
    tone: ['formal', 'casual', 'professional', 'friendly'],
    communication_style: ['padrão', 'técnico', 'casual', 'formal', 'educativo'],
    expertise_level: ['iniciante', 'intermediário', 'avançado', 'expert']
};

// Maximum lengths for string fields
const MAX_LENGTHS = {
    custom_instructions: 1000,
    industry: 100,
    inferred_profile: 2000
};

class ivaSecurityValidator {
    /**
     * Validate and sanitize iva_context (project level)
     * @param {Object} context - Raw context from user input or DB
     * @returns {Object} Sanitized and validated context
     */
    static validateEvaContext(context) {
        if (!context || typeof context !== 'object') {
            return this.getDefaultEvaContext();
        }

        const sanitized = {
            version: CONTEXT_VERSION
        };

        // Validate business_type
        if (context.business_type && ALLOWED_VALUES.business_type.includes(context.business_type)) {
            sanitized.business_type = context.business_type;
        }

        // Validate tone
        if (context.tone && ALLOWED_VALUES.tone.includes(context.tone)) {
            sanitized.tone = context.tone;
        }

        // Sanitize industry (free text but limited)
        if (context.industry && typeof context.industry === 'string') {
            sanitized.industry = this.sanitizeString(context.industry, MAX_LENGTHS.industry);
        }

        // Sanitize custom_instructions (critical - prevent injection)
        if (context.custom_instructions && typeof context.custom_instructions === 'string') {
            sanitized.custom_instructions = this.sanitizeCustomInstructions(context.custom_instructions);
        }

        // Preserve inferred_profile (generated by system, not user input)
        if (context.inferred_profile && typeof context.inferred_profile === 'string') {
            sanitized.inferred_profile = context.inferred_profile.substring(0, MAX_LENGTHS.inferred_profile);
        }

        return sanitized;
    }

    /**
     * Validate and sanitize iva_preferences (user level)
     * @param {Object} prefs - Raw preferences from user input or DB
     * @returns {Object} Sanitized and validated preferences
     */
    static validateEvaPreferences(prefs) {
        if (!prefs || typeof prefs !== 'object') {
            return this.getDefaultEvaPreferences();
        }

        const sanitized = {
            version: CONTEXT_VERSION
        };

        // Validate communication_style
        if (prefs.communication_style && ALLOWED_VALUES.communication_style.includes(prefs.communication_style)) {
            sanitized.communication_style = prefs.communication_style;
        }

        // Validate expertise_level
        if (prefs.expertise_level && ALLOWED_VALUES.expertise_level.includes(prefs.expertise_level)) {
            sanitized.expertise_level = prefs.expertise_level;
        }

        // Sanitize custom_instructions (critical - prevent injection)
        if (prefs.custom_instructions && typeof prefs.custom_instructions === 'string') {
            sanitized.custom_instructions = this.sanitizeCustomInstructions(prefs.custom_instructions);
        }

        return sanitized;
    }

    /**
     * Sanitize custom instructions to prevent prompt injection
     * @param {string} input - Raw custom instructions
     * @returns {string} Sanitized instructions
     */
    static sanitizeCustomInstructions(input) {
        if (!input || typeof input !== 'string') return '';

        let sanitized = input;

        // Remove code blocks (prevent injection of code)
        sanitized = sanitized.replace(/```[\s\S]*?```/g, '');
        sanitized = sanitized.replace(/`[^`]*`/g, '');

        // Remove potential system prompt overrides
        sanitized = sanitized.replace(/(\bsystem\b|\bAI\b|\bassistant\b|\bprompt\b):/gi, '');

        // Remove excessive newlines (prevent prompt confusion)
        sanitized = sanitized.replace(/\n{3,}/g, '\n\n');

        // Limit length
        sanitized = sanitized.substring(0, MAX_LENGTHS.custom_instructions);

        // Trim
        sanitized = sanitized.trim();

        return sanitized;
    }

    /**
     * Sanitize generic string field
     * @param {string} input - Raw string
     * @param {number} maxLength - Maximum allowed length
     * @returns {string} Sanitized string
     */
    static sanitizeString(input, maxLength = 100) {
        if (!input || typeof input !== 'string') return '';

        let sanitized = input
            .replace(/[<>]/g, '')  // Remove HTML-like tags
            .replace(/\n/g, ' ')   // Convert newlines to spaces
            .trim()
            .substring(0, maxLength);

        return sanitized;
    }

    /**
     * Get default iva_context structure
     * @returns {Object} Default context
     */
    static getDefaultEvaContext() {
        return {
            version: CONTEXT_VERSION,
            business_type: null,  // Let LLM infer
            tone: null,           // Let LLM decide
            industry: null,
            custom_instructions: '',
            inferred_profile: null
        };
    }

    /**
     * Get default iva_preferences structure
     * @returns {Object} Default preferences
     */
    static getDefaultEvaPreferences() {
        return {
            version: CONTEXT_VERSION,
            communication_style: null,  // Let LLM adapt
            expertise_level: null,      // Let LLM infer
            custom_instructions: ''
        };
    }

    /**
     * Check if iva_context needs version migration
     * @param {Object} context - Context to check
     * @returns {boolean} True if migration needed
     */
    static needsMigration(context) {
        if (!context || !context.version) return true;
        return context.version !== CONTEXT_VERSION;
    }
}

module.exports = ivaSecurityValidator;

